# Generated by Django 4.0.3 on 2022-04-15 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medicaments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meds_category', models.CharField(max_length=200)),
                ('meds_name', models.CharField(max_length=200)),
                ('meds_description', models.TextField()),
                ('meds_packing_date', models.DateTimeField(auto_now_add=True)),
                ('meds_rating', models.FloatField(default=0.0)),
                ('meds_manufacturer', models.CharField(max_length=200)),
            ],
        ),
    ]
